In [1]:
import numpy as np
print("two-dimensional array")
two_d_array = np.random.randint(1,20, size = (4,6))
print(two_d_array)
print("\nthree-dimensional array")
three_d_array = np.reshape(two_d_array,(3,4,2))
print(three_d_array)

two-dimensional array
[[16 19 19 13  4  4]
 [ 5 18  6 10 14 16]
 [18 10  8 17 11  5]
 [ 2  9 11  6 10 10]]

three-dimensional array
[[[16 19]
  [19 13]
  [ 4  4]
  [ 5 18]]

 [[ 6 10]
  [14 16]
  [18 10]
  [ 8 17]]

 [[11  5]
  [ 2  9]
  [11  6]
  [10 10]]]


In [2]:
print("two-dimensional array")
two_d_array = np.random.randint(1,20, size = (4,6))
print(two_d_array)
print("\nthree-dimensional array")
three_d_array = np.reshape(two_d_array,(1,4,2))
print(three_d_array)

two-dimensional array
[[13  8  3 10 11  3]
 [ 9 12  9  5 17  5]
 [ 8  9 14  7  8 15]
 [ 4 18 15  3  7 12]]

three-dimensional array


ValueError: cannot reshape array of size 24 into shape (1,4,2)

In [5]:
print("two-dimensional array")
two_d_array = np.random.randint(1,20, size = (4,6))
print(two_d_array)
print("\none-dimensional array")
one_d_array = two_d_array.reshape(24)
print(one_d_array)


two-dimensional array
[[ 3 17  3  8 13 16]
 [19 17  2  4 18 17]
 [14  1 10  9  1 11]
 [ 8  2 16 11  2  6]]

one-dimensional array
[ 3 17  3  8 13 16 19 17  2  4 18 17 14  1 10  9  1 11  8  2 16 11  2  6]


In [6]:
one_d_array = two_d_array.reshape(1,24)
print(one_d_array)

[[ 3 17  3  8 13 16 19 17  2  4 18 17 14  1 10  9  1 11  8  2 16 11  2  6]]


In [7]:
one_d_array = two_d_array.reshape(24,1)
print(one_d_array)

[[ 3]
 [17]
 [ 3]
 [ 8]
 [13]
 [16]
 [19]
 [17]
 [ 2]
 [ 4]
 [18]
 [17]
 [14]
 [ 1]
 [10]
 [ 9]
 [ 1]
 [11]
 [ 8]
 [ 2]
 [16]
 [11]
 [ 2]
 [ 6]]


In [8]:
print("two-dimensional array")
two_d_array = np.random.randint(1,20, size = (4,6))
print(two_d_array)
print("\none-dimensional array")
one_d_array = two_d_array.reshape(-1)
print(one_d_array)

two-dimensional array
[[12  7  8 12  6 18]
 [16  3  3  5 12  8]
 [ 4  2 11  9 14  6]
 [15  2  7 18 11 11]]

one-dimensional array
[12  7  8 12  6 18 16  3  3  5 12  8  4  2 11  9 14  6 15  2  7 18 11 11]


In [9]:
# If u pass 1 instead of -1, it will show an error.
one_d_array = two_d_array.reshape(1)
print(one_d_array)

ValueError: cannot reshape array of size 24 into shape (1,)

In [13]:
print("two-dimensional array")
three_d_array = np.random.randint(1,20, size = (5,2,6))
print(three_d_array)
print("\non-dimensional array")
one_d_array = three_d_array .reshape(-1)
print(one_d_array)


two-dimensional array
[[[ 1 15 12 14  4  5]
  [ 5 13  3 13 15  3]]

 [[ 2 14  3  5 16 11]
  [15  7  1 11  4 19]]

 [[ 3  2  8 14 11 17]
  [ 6 11  3  1 16 16]]

 [[ 2 14 13  6 17 13]
  [ 8  7 14  1  2 12]]

 [[ 4  1 14 13  3 14]
  [10  7 11  9 10 10]]]

on-dimensional array
[ 1 15 12 14  4  5  5 13  3 13 15  3  2 14  3  5 16 11 15  7  1 11  4 19
  3  2  8 14 11 17  6 11  3  1 16 16  2 14 13  6 17 13  8  7 14  1  2 12
  4  1 14 13  3 14 10  7 11  9 10 10]


In [14]:
s = np.arange(1,11)
print(s)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
# The item at index one can be accessed as follows:
import numpy as np
s = np.arange(1,11)
print(s)
print(s[1])

[ 1  2  3  4  5  6  7  8  9 10]
2


In [16]:
# To slice an array, you have to pass the lower index, followed by a colon and
# the upper index. The items from the lower index (inclusive) to the upper
# index (exclusive) will be filtered. The following script slices the array “s”
# from the 1st index to the 9th index. The elements from index 1 to 8 are
# printed in the output.

s = np.arange(1,11)
print(s)
print(s[1:9])

[ 1  2  3  4  5  6  7  8  9 10]
[2 3 4 5 6 7 8 9]


In [17]:
# If you specify only the upper bound, all the items from the first index to the
# upper bound are returned. Similarly, if you specify only the lower bound, all
# the items from the lower bound to the last item of the array are returned.

s = np.arange(1,11)
print(s)
print(s[:5])
print(s[5:])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]
[ 6  7  8  9 10]


In [18]:
# Array slicing can also be applied on a two-dimensional array. To do so, you
# have to apply slicing on arrays and columns separately. A comma separates
# the rows and columns slicing. In the following script, the rows from the
# first and second indexes are returned, while all the columns are returned.
# You can see the first two complete rows in the output.

row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]
nums_2d = np.array([row1, row2, row3])
print(nums_2d[:2,:])

[[10 12 13]
 [45 32 16]]
